title: Agostini Arthur # your name (or website title) here
Photo: "images/profil2.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a data science engineer
  Passionate about new technologies, space exploration, and the blockchain environment (yes, I am a bit of a geek). 
  
  I have participated in different projects that have allowed me to develop my data collection, processing, and analysis skills. 
  My commitment to discovering new technologies and continuously learning has led me to present my latest work at the 3DBodyTech 2022 conference. 
  This experience has pushed me out of my comfort zone. 
  
  Always ready to meet new people and collaborate on exciting projects that will allow me to continue learning and growing as a professional while surrounded by a dynamic and inspiring environment.
  <br><br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/arthur-agostini-a17287160/">Want to connect with LinkedIn</a> 
  
theme: jekyll-theme-minimal
